### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jcohen66** [AgentOps-AI/AgentStack#142]
### Contact Details

jcohen66g@gmail.com

### 📦 Package Version

0.2.2.2

### 🔎 Describe the Bug

I am getting this when ansering 'N' to 

[?] Do you want to add agent tools now? (you can do this later with `agentstack tools add <tool_name>`) (y/N):

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jcohe\anaconda3\Scripts\agentstack.exe\__main__.py", line 7, in <module>
  File "C:\Users\jcohe\anaconda3\Lib\site-packages\agentstack\main.py", line 116, in main
    init_project_builder(args.slug_name, args.template, args.wizard)
  File "C:\Users\jcohe\anaconda3\Lib\site-packages\agentstack\cli\cli.py", line 102, in init_project_builder
    design = ask_design()
             ^^^^^^^^^^^^
  File "C:\Users\jcohe\anaconda3\Lib\site-packages\agentstack\cli\cli.py", line 259, in ask_design
    if not agent['name'] or agent['name'] == '':
           ~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

### 🤝 Contribution

- [ ] Yes, I'd be happy to submit a pull request with these changes.
- [ ] I need some guidance on how to contribute.
- [ ] I'd prefer the AgentStack team to handle this update.

**Comment by bboynton97** [comment]
Fixed with #147
