### ISSUE TITLE
[Bug]: Petry install doesnt work

### ISSUE THREAD

**Issue by M4A1SD** [AgentOps-AI/AgentStack#171]
### 📦 Package Version

AgentStack CLI version: 0.2.2.2

### 🔎 Describe the Bug

I have fresh python 3.12 install with new venv. i follwo these steps 

create and activate venv
pip install -U poetry

I get 
```(.venv_web_scraper) PS D:\GitHub\AI-agent\web_scraoer> poetry install
Updating dependencies
Resolving dependencies... (7.4s)

failed to build image setuptools because:
Traceback (most recent call last):
  File "D:\GitHub\AI-agent\web_scraoer\.venv_web_scraper\Lib\site-packages\virtualenv\seed\embed\via_app_data\via_app_data.py", line 59, in _install
    installer.install(creator.interpreter.version_info)
  File "D:\GitHub\AI-agent\web_scraoer\.venv_web_scraper\Lib\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 39, in install
    self._sync(filename, into)
  File "D:\GitHub\AI-agent\web_scraoer\.venv_web_scraper\Lib\site-packages\virtualenv\seed\embed\via_app_data\pip_install\copy.py", line 13, in _sync
    copy(src, dst)
  File "D:\GitHub\AI-agent\web_scraoer\.venv_web_scraper\Lib\site-packages\virtualenv\util\path\_sync.py", line 43, in copy
    method(str(src), str(dest))
  File "D:\GitHub\AI-agent\web_scraoer\.venv_web_scraper\Lib\site-packages\virtualenv\util\path\_sync.py", line 54, in copytree
    shutil.copy(src_f, dest_f)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\shutil.py", line 435, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\shutil.py", line 260, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\bld93\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\Local\\pypa\\virtualenv\\wheel\\3.12\\image\\1\\CopyPipInstall\\setuptools-75.6.0-py3-none-any\\pkg_resources\\tests\\data\\my-test-package_zipped-egg\\my_test_package-1.0-py3.7.egg'
```
pip list 
```(.venv_web_scraper) PS D:\GitHub\AI-agent\web_scraoer> pip list
Package              Version
-------------------- -------------
build                1.2.2.post1
CacheControl         0.14.1
certifi              2024.12.14
charset-normalizer   3.4.1
cleo                 2.1.0
colorama             0.4.6
crashtest            0.4.1
distlib              0.3.9
dulwich              0.21.7
fastjsonschema       2.21.1
filelock             3.16.1
idna                 3.10
installer            0.7.0
jaraco.classes       3.4.0
keyring              24.3.1
more-itertools       10.5.0
msgpack              1.1.0
packaging            24.2
pexpect              4.9.0
pip                  24.3.1
pkginfo              1.12.0
platformdirs         4.3.6
poetry               1.8.5
poetry-core          1.9.1
poetry-plugin-export 1.8.0
ptyprocess           0.7.0
pyproject_hooks      1.2.0
pywin32-ctypes       0.2.3
RapidFuzz            3.11.0
requests             2.32.3
requests-toolbelt    1.0.0
shellingham          1.5.4
tomlkit              0.13.2
trove-classifiers    2024.10.21.16
urllib3              2.3.0
virtualenv           20.28.0```
```

Couldnt figure this with gpt for couple hourse... gave up

**Comment by bboynton97** [comment]
Closing this as poetry has now been replaced with UV
