### ISSUE TITLE
`agentstack run` checks for valid project

### ISSUE THREAD

**Issue by bboynton97** [AgentOps-AI/AgentStack#60]
When running `agentstack run`, the CLI should first check that the project is valid.

At this time, "valid" means that the project has at least one agent and one task.

**Comment by bboynton97** [comment]
This is in response to a discord support question from a user that ran
```bash
agentstack init
agentstack run
```
and received this error
```
/home/vscode/.cache/pypoetry/virtualenvs/silly-agent-d-U8PDVS-py3.12/lib/python3.12/site-packages/pysbd/segmenter.py:66: SyntaxWarning: invalid escape sequence '\s'
  for match in re.finditer('{0}\s*'.format(re.escape(sent)), self.original_text):
/home/vscode/.cache/pypoetry/virtualenvs/silly-agent-d-U8PDVS-py3.12/lib/python3.12/site-packages/pysbd/lang/arabic.py:29: SyntaxWarning: invalid escape sequence '\.'
  txt = re.sub('(?<={0})\.'.format(am), '∯', txt)
/home/vscode/.cache/pypoetry/virtualenvs/silly-agent-d-U8PDVS-py3.12/lib/python3.12/site-packages/pysbd/lang/persian.py:29: SyntaxWarning: invalid escape sequence '\.'
  txt = re.sub('(?<={0})\.'.format(am), '∯', txt)
🖇 AgentOps: Session Replay: https://app.agentops.ai/drilldown?session_id=d1551dfb-60f6-43cd-b024-0ad4e414cf76
🖇 AgentOps: Session Stats - Duration: 0.8s | Cost: $0.00 | LLMs: 0 | Tools: 0 | Actions: 0 | Errors: 0
🖇 AgentOps: Session Replay: https://app.agentops.ai/drilldown?session_id=d1551dfb-60f6-43cd-b024-0ad4e414cf76
Traceback (most recent call last):
  File "/workspaces/agentops-playground/silly_agent/src/main.py", line 65, in <module>
    run()
  File "/workspaces/agentops-playground/silly_agent/src/main.py", line 22, in run
    SillyagentCrew().crew().kickoff(inputs=inputs)
    ^^^^^^^^^^^^^^^^
  File "/home/vscode/.cache/pypoetry/virtualenvs/silly-agent-d-U8PDVS-py3.12/lib/python3.12/site-packages/crewai/project/crew_base.py", line 32, in __init__
    self.map_all_agent_variables()
  File "/home/vscode/.cache/pypoetry/virtualenvs/silly-agent-d-U8PDVS-py3.12/lib/python3.12/site-packages/crewai/project/crew_base.py", line 70, in map_all_agent_variables
    for agent_name, agent_info in self.agents_config.items():
                                  ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'items'
```
